### ISSUE TITLE
Trailer button is not shown in Jellyfin MPV Shim-desktop

### ISSUE THREAD

**Issue by chp-1960** [jellyfin/jellyfin-mpv-shim#104]
**Describe the bug**
The trailer button (in the movie details) is shown and working at the very first launch of Jellyfin MPV Shim-desktop. But after this very first launch, and at every new launch this button is not shown anymore.

**To Reproduce**
While investigating, I found something interesting :

If I disconnect from the cast button, I retrieve the ability to see the trailer button and to play them. The downside is I'm not able to see my own movie resulting a Playback Error : "This client isn't compatible with the media and the server isn't sending a compatible media format."

If I reconnect from the cast button, I retrieve the ability to see the movies but no more the trailer button.

In any cases, I have the ability to see trailers and my movies from the WEB Browser

**Expected behavior**
The trailer button should be available (and working) while in Cast mode.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10 64bits (x64) and Windows 10 32bits (x86)
 - Version : All

**Comment by iwalton3** [comment]
The Jellyfin Web Client is currently undergoing some major rewrites in upstream. I will likely wait until the migration to ES6 modules is done at the very least before looking at this.

If you'd like to open an issue with jellyfin-web, you can do that. Otherwise I'll look at it after that rewrite is complete.

**Comment by chp-1960** [comment]
Hi,

Dates are forcasted for these rewrites ?

Cordialement,
Laurent CHIRIC.


De : Ian Walton<mailto:notifications@github.com>
Envoyé le :dimanche 16 août 2020 16:25
À : iwalton3/jellyfin-mpv-shim<mailto:jellyfin-mpv-shim@noreply.github.com>
Cc : chp-1960<mailto:chp_1960@hotmail.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [iwalton3/jellyfin-mpv-shim] Trailer button is not shown in Jellyfin MPV Shim-desktop (#104)


The Jellyfin Web Client is currently undergoing some major rewrites in upstream. I will likely wait until the migration to ES6 modules is done at the very least before looking at this.

If you'd like to open an issue with jellyfin-web, you can do that. Otherwise I'll look at it after that rewrite is complete.

**Comment by iwalton3** [comment]
I have no idea, but the initial ones are going fairly quickly. Maybe a month or so?

I'll still do break/fix work for jellyfin-web, but I've already gotten stuck re-writing integration code once.

**Comment by chp-1960** [comment]
Many thanks for your kindly concern.

I have one more question I’m very concerned and perahps you can reply :
I own 2 Jellyfin servers : 1 working on a powerfull DELL on Windows 64bit for home and remote access and another one based on an old micro-PC based on an Atom z37xx and acting as a NAS (with 4TB HDD and 8000mA included Battery) I mainly use when I travel from countries without Internet access at the hotel. This one accept only Windows 32bits because of the 32bits UEFI BIOS (even if the proc is 32/64bits).
With the lattests Jellyfin builds, only for 64bits, I’m stuck with Jellyfin v1.5.5 (the latest build as a portable 32bits).

So, my question is : Do you know if Jellyfin devs plan to continue to make a 32bits build ?

Regards,
Laurent CHIRIC.


De : Ian Walton<mailto:notifications@github.com>
Envoyé le :dimanche 16 août 2020 16:32
À : iwalton3/jellyfin-mpv-shim<mailto:jellyfin-mpv-shim@noreply.github.com>
Cc : chp-1960<mailto:chp_1960@hotmail.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [iwalton3/jellyfin-mpv-shim] Trailer button is not shown in Jellyfin MPV Shim-desktop (#104)


I have no idea, but the initial ones are going fairly quickly. Maybe a month or so?

I'll still do break/fix work for jellyfin-web, but I've already gotten stuck re-writing integration code once.

**Comment by iwalton3** [comment]
I'm not sure. I know I only started providing 32 bit support by request, as all of my hardware is 64 bit. Honestly, I'm really surprised there is still 32 bit only hardware out there.

As for any official stance on 32 bit Windows builds, it looks like they were removed when they re-did the build infrastructure. 

https://github.com/jellyfin/jellyfin/commit/fbad4f00b4a95b889708d430ad445a58dad2f964#diff-06e5c0d0f9eabd9525e5f9dc4f6f37cf

Since Jellyfin is written in .NET, you *might* be able to get the portable version running on Windows 32 bit? I haven't tried it and don't have any 32 bit systems anymore. You'd need the .net core runtime installed, and might also have to install ffmpeg separately. https://repo.jellyfin.org/releases/server/portable/stable/combined/jellyfin_10.6.2.tar.gz

**Comment by chp-1960** [comment]
You’re right.

The 32bit .NET (3.5 & 4.x) is included in Windows since years (except if we need Something else ?) and I know how to change the ffmpeg by myself. Eventually I can use the one included in v1.5.5 if I can’t find a newer on the web.

Ok, Now the results of your test build (I can’t see the version) :

I downloaded your test build (huge one). Here are my feedback :
IT works as v1.5.11 meaning :

  *   I can open sessions on my 32bit micro-PC (based on JF v10.5.5)
  *   I can open sessions on my 64bis server (based on JF 10.6.2)
  *   Browsing the folders and library works
  *   I can play my movies on the 2 servers
  *   Still the behavior with the Trailers button

Regards,
Laurent CHIRIC.


De : Ian Walton<mailto:notifications@github.com>
Envoyé le :dimanche 16 août 2020 17:01
À : iwalton3/jellyfin-mpv-shim<mailto:jellyfin-mpv-shim@noreply.github.com>
Cc : chp-1960<mailto:chp_1960@hotmail.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [iwalton3/jellyfin-mpv-shim] Trailer button is not shown in Jellyfin MPV Shim-desktop (#104)


I'm not sure. I know I only started providing 32 bit support by request, as all of my hardware is 64 bit. Honestly, I'm really surprised there is still 32 bit only hardware out there.

As for any official stance on 32 bit Windows builds, it looks like they were removed when they re-did the build infrastructure.

jellyfin/jellyfin@fbad4f0#diff-06e5c0d0f9eabd9525e5f9dc4f6f37cf<https://github.com/jellyfin/jellyfin/commit/fbad4f00b4a95b889708d430ad445a58dad2f964#diff-06e5c0d0f9eabd9525e5f9dc4f6f37cf>

Since Jellyfin is written in .NET, you might be able to get the portable version running on Windows 32 bit? I haven't tried it and don't have any 32 bit systems anymore. You'd need the .net core runtime installed, and might also have to install ffmpeg separately. https://repo.jellyfin.org/releases/server/portable/stable/combined/jellyfin_10.6.2.tar.gz

**Comment by iwalton3** [comment]
Desktop mode is now unsupported and is removed in the latest release. Please use Shim Mode or [Jellyfin Media Player](https://github.com/jellyfin/jellyfin-media-player/releases) instead.

**Comment by chp-1960** [comment]
Hi iwalton3,



It's been a long time since we last talked. If I have no longer contacted you it is because the information you gave me was applied and gave full satisfaction.


Now, II am in the process of making a big switch to Linux (Kubuntu 22.04 LTS) and I'm facing problems managing 5.1 audio outputs aver HDMI (AC3, DTS, EAC3, ...) with Jellyfin MPV-Shim and Jellyfin Media Player. My Jellyfin Server is on another computer and work fine for all the Windows clients I have.



Here are my problems:

Note: MPV and VLC work perfectly in 5.1 on the HDMI output in PULSE mode with test video files in 5.1 ac3.


  *
In Jellyfin MPV-Shim : it does not take into account the MPV.conf file which I copied into the MPV-Shim configuration directory and which is identical to the "standard" MPV (/etc/mpv) and which works fine with MPV. I only get "stereo" sound at best and I think that MPV-Shim does not take native MPV into account and use it's own version of MPV or is sandboxed.
  *
In Jellyfin Media Player : Whatever the audio configuration in the "Client Configuration" section, and sound card (correctly set), I only get stereo sound at best. If I configure AC3 (and/or DTS) passthrough, I simply dont get any sound.
I also tried to copy and use my MPV.conf file into "/jellyfinmediaplayer/25/.local/share/jellyfinmediaplayer/" as I read on the forums. It look like JMP read the file but don't care about the values (attached log file).

 /jellyfinmediaplayer/25/.local/share/jellyfinmediaplayer/

Questions :

  *   is it possible to install the MPV-Shim binaries without using flatpack (any ppa: repos) ?
  *
How to configure MPV-Shim to take into account the native MPV installed in Ubuntu and whose configuration file is in /etc/mpv?
  *
What values should be set in Jellyfinmediaplayer.conf to activate the HDMI multichannel audio over HDMI.
  *   What values, in Jellyfinmediaplayer.conf, need to be changed to "force" to use the native MPV? all my attempts have failed (my Jellyfinmediaplayer.conf file attached).



You'll find attached my mpv.conf I use both for MPV, Jellyfin Media Player and Jellyfin MPV-Shim. And Jellyfinmediaplayer.conf and Jellyfinmediaplayer.log files I use for Jellyfin Media Player


Please, help me to solve these audio problems. These are the last points who prevent me to finish this Linux move.


Regards,

CHP
