### ISSUE TITLE
Subtitles Pagination

### ISSUE THREAD

**Issue by dgalli1** [jellyfin/jellyfin-mpv-shim#109]
Today i got my hands on a video file with 28 subtitles. The list is to long to Display in the OSD.
![grafik](https://user-images.githubusercontent.com/6371945/90923772-8ddcc980-e3ee-11ea-92ed-1114d8a8b4f8.png). And with that im not able to set the subtitle for the whole season.

I initially thought this could be solved easly by just shifting the whole list by a position if you are at the latest visible subtitle. But this doesn't work anymore since you added mouse support. So i guess the best possibility would be to add a arrows (<- / ->) at the bottom to go to the next page.

**Comment by dgalli1** [comment]
Sorry for the bump. But got an idea how to handle it better (in my opinion).
Filtering the subtitles is not really needed when we only have less then 8 subtitles or something because we can see them.
The badly named subtitles are also almost always in files with not that many subtitles.
Don't you think it would be a good idea to give an option only filter if a certain number of subtitles is present in the current file?

**Comment by iwalton3** [comment]
I thought about that, but if you set the filter correctly you should never have to disable it. It will allow untagged and misc-purpose subtitles, only removing ones that are in another language that you didn't specify.

Do you have files that are tagged in a language that you wouldn't specify in the configuration file? I actually [outright delete these](https://github.com/iwalton3/media-scripts/tree/master/media-discard) using a script and have never had issues.

**Comment by dgalli1** [comment]
> It will allow untagged and misc-purpose subtitles, only removing ones that are in another language that you didn't specify.
Nah sorry your right, i didn't look that closely at your commit. And oversaw your comment with untagged subtitles. Current implementation should be just fine. Thanks for clarifying.
