### ISSUE TITLE
How to change the player interface to make it look better or closer to the Jellyfin Web player interface?

### ISSUE THREAD

**Issue by rubensgpl** [jellyfin/jellyfin-mpv-shim#150]
I'm new to Jellyfin MPV and just loved it. My computer utilization when watching a 1080p movie with Jellyfin Web (in Firefox or Edge) reaches 80%, but with Jellyfin MPV it doesn't even reach 30%. Everything is working fine, the only thing that is confusing to me is the player interface and the main menu. Could I improve the player's visual or maybe make it look like the standard Jellyfin Web player, with the same buttons, icons, color, and so on?

Example:
![image](https://user-images.githubusercontent.com/2881202/103711452-3bafd580-4f96-11eb-8d82-0292940de5cc.png)

**Comment by rubensgpl** [comment]
I have been playing with MPV and reading their documentation to understand how it works. I'm able to modify the player interface (OSC) using some LUA scripts and making configurations with `input.conf` and `mpv.conf`. I thought that copying all the files listed in the MPV's config folder and pasting it inside Jellyfin MPV's config folder, would have the same effect over the interface, keyboard shortcuts and other configurations I have set to play movies. Turns out it doesn't seem to take effect in Jellyfin's player, as if the conf files and LUA scripts were not loading. What am I doing wrong?

**Comment by thomasdaley2** [comment]
This gui improvemtns (plus an exit button) would make this a top level client

**Comment by rubensgpl** [comment]
@thomasdaley2 If the OSC Lua scripts that change the MPV's interface worked here, that would be a big step to make its interface better. But like I said, maybe I'm doing something wrong to install the scripts. I'll wait for an answer from the developers.

**Comment by iwalton3** [comment]
You need to specify lua scripts in the config file for them to work. I don't currently import scripts into MPV that are specified in the directory automatically.

Scripts tweaking the UI may have unintentional effects on the menu UI. If you would like to propose a better UI for that, be my guest.

In the long run I intend to make the default experience a QT UI with MPV embedded just as a playback engine. I intend to support shim mode's UI as well. I do not intent to maintain the web wrapper indefinitely.

**Comment by thomasdaley2** [comment]
Thanks for your reply, I love this windows client and appreciate the work you are doing on it.  Looking forward to your future changes.

**Comment by rubensgpl** [comment]
@iwalton3 I'm just a regular user and don't know how to specify the scripts in the config file, can you help me? I would like to test a [lua script that changes the UI](https://github.com/maoiscat/mpv-osc-morden). I wish I could propose a better UI, but I don't know how to code yet, still learning.

**Comment by thomasdaley2** [comment]
Thanks for your reply, I love this windows client and appreciate the work you are doing on it.  Looking forward to your future changes.

> @iwalton3 I'm just a regular user and don't know how to specify the scripts in the config file, can you help me? I would like to test a [lua script that changes the UI](https://github.com/maoiscat/mpv-osc-morden). I wish I could propose a better UI, but I don't know how to code yet, still learning.

Try having a look here, https://github.com/jonniek/mpv-scripts
Might lead you to learning resources and some of those scripts are interesting.... I'm no coder but I may try to see if I can implement the menu one to add a quit function.

**Comment by iwalton3** [comment]
You need to specify the full path to the script in the config file with the script parameter.

**Comment by iwalton3** [comment]
Jellyfin Media Player is a new player that does this! Read about it here: https://jellyfin.org/posts/client-jmp/

Desktop mode is now unsupported and is removed in the latest release. Please use Shim Mode or [Jellyfin Media Player](https://github.com/jellyfin/jellyfin-media-player/releases) instead.
