### ISSUE TITLE
Windows Desktop Client's width and height increases on exit

### ISSUE THREAD

**Issue by TheClaus** [jellyfin/jellyfin-mpv-shim#162]
**Describe the bug**
When using the following settings within the conf.json and then running the desktop client and exiting the client the width and height increase each time.

`"desktop_fullscreen": false,
"desktop_keep_pos": true,
"desktop_keep_size": true,`

When the client is exited the layout.json changes everytime.

**To Reproduce**
1. Set the following options on conf.json
    "desktop_fullscreen": false,
    "desktop_keep_pos": true,
    "desktop_keep_size": true,
2. Run Jellyfin MPV Desktop Client
3. Resize client and move client window
4. Exit client
5. Check width and height in layout.json
6. Run Jellyfin MPV Desktop Client and exit back out
7. Check width and height in layout.json and they will have increased

**Expected behavior**
Desktop client should retain settings that were set by the user upon exiting.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.8.0

**Comment by iwalton3** [comment]
Desktop mode is now unsupported and is removed in the latest release. Please use Shim Mode or [Jellyfin Media Player](https://github.com/jellyfin/jellyfin-media-player/releases) instead.
