### ISSUE TITLE
Add Possibility to control media playing like web browser 

### ISSUE THREAD

**Issue by apierre55000** [jellyfin/jellyfin-mpv-shim#201]
hello
it could be very cool to add the possibility to control media like the browser
with the popup layer of windows 10 and with keyboard shortcuts
thank you :)

**Comment by iwalton3** [comment]
What do you mean by that? Like with the same player interface as the web client?

If so look at this new project: https://github.com/iwalton3/jellyfin-media-player

**Comment by apierre55000** [comment]
![media-player-win10-controls_medium](https://user-images.githubusercontent.com/64436743/113850515-d8069580-979a-11eb-919d-49683101804c.jpg)

do you know this shortcut on windows 10 to control all the playing medias ? it could cool that jellyfin desktop interact with it :)

**Comment by iwalton3** [comment]
Note: This has been implemented in Jellyfin Media Player (the other Jellyfin client) in https://github.com/jellyfin/jellyfin-media-player/pull/73 and will be in the next release.

**Comment by apierre55000** [comment]
ok super than you :)
