### ISSUE TITLE
Theme song support for TV Shows

### ISSUE THREAD

**Issue by vegedb** [jellyfin/jellyfin-mpv-shim#202]
Under Display>
![image](https://user-images.githubusercontent.com/72070424/113756972-a4008580-9744-11eb-87b5-3766fcac5675.png)

This doesn't work on MPV Desktop, but works on web interface.

**Comment by iwalton3** [comment]
Desktop mode is now unsupported and is removed in the latest release. Please use Shim Mode or [Jellyfin Media Player](https://github.com/jellyfin/jellyfin-media-player/releases) instead.
