### ISSUE TITLE
Font in thumbnails too large in v1.10

### ISSUE THREAD

**Issue by gggirlgeek** [jellyfin/jellyfin-mpv-shim#208]
Hello,

The font in the Home screen thumbnails is now too large compared to version 1.8. I can't read the title when shows are unidentified and don't have an image for the thumbnail (the filename.) I have tried changing to "desktop_scale": 0.8 in the conf.json file, but it only made the thumbnails smaller without changing the font. In Jellyfin Web I am able to change the zoom level and the font size gets smaller. Is there a way to do this with Jellyfin MPV desktop? 

![JellyfinMediaPlayer_WMbduryrJb (2)](https://user-images.githubusercontent.com/2652614/115310403-008f7780-a12b-11eb-8f88-a67279764e29.jpg)
Jellfin MPV Desktop

![firefox_h9qBjLkm4f](https://user-images.githubusercontent.com/2652614/115310456-11d88400-a12b-11eb-833b-1a0da9677206.png)
Jellyfin Web

Win10pro v2004
1920x1080 DPI 125%
Jellyfin MPV Desktop 1.10.4
Jellyfin Server v10.6.x on Ubuntu 18.6 managed seedbox

**Comment by iwalton3** [comment]
Desktop mode is now unsupported and is removed in the latest release. Please use Shim Mode or [Jellyfin Media Player](https://github.com/jellyfin/jellyfin-media-player/releases) instead.
