### ISSUE TITLE
Clarify GPL license version used

### ISSUE THREAD

**Issue by jojosch** [jellyfin/jellyfin-mpv-shim#210]
Hey,

i am currently maintaining packages for `jellyfin-mpv-shim`, `jellyfin-media-player` and `jellyfin-apiclient-python` in [NixOS/nixpkgs](https://github.com/NixOS/nixpkgs).

Currently these three projects state that they are licensed under GPLv3 (shim and apiclient) and GPLv2 (media-player). However, our packaging guidelines now require that it be explicitly stated whether `GPL-X-only` or `GPL-X-or-later` is to be used. See https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md for an overview.

Hence my question: which license version of the GPL should be specified for the three projects?

**Comment by iwalton3** [comment]
I can confirm all the projects are available only under the respective license and not a later version, as there is no language anywhere that specifies a later version is permitted. An attempt to change this would require all contributors to re-license their contributions.
