### ISSUE TITLE
Subtitles and the menu are blurry with shim-only releases.

### ISSUE THREAD

**Issue by maru801** [jellyfin/jellyfin-mpv-shim#211]
**Describe the bug**
It seems with the removal of the desktop mode, the menu and subtitles are now blurry. Thinking it was the new v2.0.0 release, I tested the previous shim-only release for v1.10.4 and that had the same problem. It seems this is due to desktop mode being gone.

**To Reproduce**
1. Install the v.2.0.0 release
2. Open the menu in the player and see how the menu becomes blurry as well as any playing subtitle

**Expected behavior**
For menu text and subtitles to not be blurry during playback

**Screenshots**
v1.10.4 Desktop Shim-menu: https://i.imgur.com/gogRQdv.jpg
v1.10.4 Desktop Shim-subs: https://i.imgur.com/1cNSoee.jpg

v2.0.0 Menu: https://i.imgur.com/C3MXzKQ.jpg
v2.0.0 Subs: https://i.imgur.com/Lils5FZ.jpg

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.0.0

**Error Messages**
[log.txt](https://github.com/jellyfin/jellyfin-mpv-shim/files/6348713/log.txt)
Just in case it might be due to dpi, I have this running on a computer with a 4k screen.

**Comment by iwalton3** [comment]
The only thing I can find is that it might be the output driver. The MPV version did not change so unless desktop mode inadvertently broke an output mode I am not sure. Please post logs with MPV set to "v" debug level for the old and new playback attempts.

You may want to try changing the scaling settings? There's not a lot of resources about this.

**Comment by maru801** [comment]
After doing some more testing, I also realized the playback slider menu at the bottom would also turn blurry. I also followed your advice and changed the dpi settings for the shim executable and tried all 3 settings.

In the executable compatibility settings, for "Override high DPI scailing behavior. Scaling performed by:", selecting "System" & "System (Enhanced)" didn't fix the issue. However, choosing the scaling to be performed by "Application" fixed it and everything looks as sharp as it should. No more blurring of the menus, sliders, and subtitles. 
Here is a screenshot of the setting I chose: https://i.imgur.com/gmUpqPL.jpg

Here are the logs that you requested. Tell me if I messed up with changing the logs to the "v" debug level.
[log(v1.10.4).txt](https://github.com/jellyfin/jellyfin-mpv-shim/files/6353023/log.v1.10.4.txt)
[log(v2.0.0).txt](https://github.com/jellyfin/jellyfin-mpv-shim/files/6353024/log.v2.0.0.txt)

I'm using the same stock windows 10 4k dpi scaling (3840x2160 at 250% scaling) as when I first got the computer. I did some more tests and reverted to 4k at 100% scaling (without changing the executable dpi settings this time), and this also fixed the issue with everything looking sharp.

I find this odd since I also installed the latest Jellyfin Media Player version, and that plays find without adding a blur to the subtitles without needing to change the dpi settings.

**Comment by iwalton3** [comment]
> Override high DPI scailing behavior

Oh. I removed a HiDPI manifest because I thought I only needed it for the desktop mode. I will have a fix out with that manifest added back, as we definitely do not want the OS to upscale everything into a blurry mess...

**Comment by iwalton3** [comment]
Fixed in v2.0.1.
