### ISSUE TITLE
enable_osc: false doesn't fully disable default mpv OSC

### ISSUE THREAD

**Issue by whiteworthy** [jellyfin/jellyfin-mpv-shim#212]
Opening mpv shims menu shows the default mpv OSC even though enable_osc is set to false, older versions (user feedback release) didn't have this issue.

**To Reproduce**
1. Set enable_osc to false
2. Open mpv shim's menu and close it with ESC
3. Default MPV OSC appears

**Expected behavior**
Default OSC is fully disabled as it used to be.

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Version: Latest (Portable)

**Comment by iwalton3** [comment]
Fixed in v2.0.1.
