### ISSUE TITLE
A "PlaybackStopEvent" should be fired on music track changes

### ISSUE THREAD

**Issue by Dperrigo18** [jellyfin/jellyfin-mpv-shim#215]
This is needed for last.fm scrobbling to work properly.
Is it possible for this to be added.

Here is a detailed description of the last.fm plugin behavior:
https://github.com/jesseward/jellyfin-plugin-lastfm/issues/27#issuecomment-744031810

**Comment by iwalton3** [comment]
Does this test build fix the problem? https://github.com/jellyfin/jellyfin-mpv-shim/suites/2618644993/artifacts/57380541

(If you are using Linux you'll need to [follow these instructions](https://github.com/jellyfin/jellyfin-mpv-shim#local-dev-installation).)

**Comment by Dperrigo18** [comment]
So when I play a single song through the Desktop app it seems to work and scrobbles correctly to last.fm but if it is a queue of songs it does not seem to work.

Also thanks on the quick reply.

**Comment by iwalton3** [comment]
Please note the desktop app has been discontinued and you should be using https://github.com/jellyfin/jellyfin-media-player instead.

If the shortcut is still present and works that is not intended.

**Comment by Dperrigo18** [comment]
So using just the mpv-shim it does look like it is working properly now between songs.

Thanks for the help!
