### ISSUE TITLE
Subtitle formatting reverting to MPV defaults since transition away from Desktop Client

### ISSUE THREAD

**Issue by MrSegi** [jellyfin/jellyfin-mpv-shim#217]
**Describe the bug**
MPV default subtitle formatting is being used instead of the embedded .ass formatting.

**Screenshots**
Played with MPV:
![mpv-shot0001](https://user-images.githubusercontent.com/17787212/117095800-967af300-ad24-11eb-8732-c49a358ce25c.jpg)

Played with web interface (no casting):
![brave_2021-05-04_21-45-23](https://user-images.githubusercontent.com/17787212/117095818-a4c90f00-ad24-11eb-81e7-9b7b67670dd6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Error Messages**
[log.txt](https://github.com/jellyfin/jellyfin-mpv-shim/files/6425035/log.txt)

**Comment by iwalton3** [comment]
Your video is transcoding. Transcoding loads subtitles externally which loses fonts. Maybe see if your bandwidth limit can be higher.

**Comment by MrSegi** [comment]
I have bandwidth settings set to as high as they can go. Server version is 10.7.4, I'll try with the old desktop mode and see if I get the same results.

![run_2021-05-04_22-32-14](https://user-images.githubusercontent.com/17787212/117097518-215dec80-ad29-11eb-8256-c4df10eb220d.png)
![brave_2021-05-04_22-34-42](https://user-images.githubusercontent.com/17787212/117097525-2327b000-ad29-11eb-8e70-5c1074b88422.png)
![brave_2021-05-04_22-34-15](https://user-images.githubusercontent.com/17787212/117097528-2458dd00-ad29-11eb-847a-6f15898f79dd.png)

**Comment by iwalton3** [comment]
Upgrade to server version 10.7.5. 10.7.4 is a bad release that always transcoded media for no reason.

**Comment by MrSegi** [comment]
That ended up working, thank you. Sorry for the trouble.
