### ISSUE TITLE
Why is desktop mode removed and what is shim mode please?

### ISSUE THREAD

**Issue by gggirlgeek** [jellyfin/jellyfin-mpv-shim#220]
Hello,

There is really no clear explanation of what shim mode is and why desktop mode was removed. The front page assumes we know what a shim is?

Jellyfin Media Player is still not advanced enough to replace this because it does not support keyboard shortcuts. Specifically, we cannot adjust the audio sync yet. All of my streamed videos seem to need this so it is a deal breaker for me. 

Win10 x64
MPV Desktop 1.10.4
Jellyfin Server 10.6 on Ubuntu 18 Seedbox

**Comment by iwalton3** [comment]
More details here: https://github.com/jellyfin/jellyfin-mpv-shim/releases/tag/v2.0.0

Please use the discussion board for questions.
