### ISSUE TITLE
The 'jellyfin-apiclient-python>=1.8.1' is required but there is no 1.8.1 tag

### ISSUE THREAD

**Issue by nahsi** [jellyfin/jellyfin-mpv-shim#248]
I'm using portage package manager. In order to install `jellyfin-apiclient-python` version `1.8.1` tag in github should exist (portage will download artifact from github).

![image](https://user-images.githubusercontent.com/28529663/147854286-7d8d865d-ceb5-45c4-b307-beb9a3ee34be.png)

**Comment by iwalton3** [comment]
Fixed. I forgot to actually push the tag.
