### ISSUE TITLE
Windows Installation broken (2.0.2)

### ISSUE THREAD

**Issue by traits** [jellyfin/jellyfin-mpv-shim#252]
Installation from `jellyfin-mpv-shim_2.0.2_installer.exe` on top of my 2.0.1 installation creates a new shortcut:

`C:\Users\XXX\AppData\Local\Programs\Jellyfin Desktop\run.exe`
old one was
`C:\Users\XXX\AppData\Local\Programs\Jellyfin Desktop\run-desktop.exe` (quite possible, this one was created manually from me, I don't remember. But it was working in starting the GUI)

Running the new shortcut produces an entry at the right taskbar area providing a submenu with five entries:

```
Configure Servers
Show Console
Application Menu
[...]
```
None of these do anything useful. Pressing the shortcut again will add more instances of this toolbar app.

Trying the old shortcut gives a message:

`Failed to execute script pyi_rth_win32comgenpy`

**Comment by iwalton3** [comment]
Desktop mode has been removed. See details here: https://github.com/jellyfin/jellyfin-mpv-shim/releases/tag/v2.0.0

I suggest using this instead: https://github.com/jellyfin/jellyfin-media-player/releases
