### ISSUE TITLE
Cannot use external mpv player 

### ISSUE THREAD

**Issue by Zabooby** [jellyfin/jellyfin-mpv-shim#266]
I have a mpv setup that I've spent ages perfecting and wanted jellyfin to use it. I've installed mpv-shim and followed the steps on github to use an external player. Here is the relevant part of the conf.json, I am on windows 11.

```
"mpv_ext": true,

"mpv_ext_ipc": null,

"mpv_ext_no_ovr": false,

"mpv_ext_path": C:\\Program Files\\mpv\\mpv.exe,

"mpv_ext_start": true,
```
Currently when I start a video it opens mpv externally but not my setup.

**Comment by Zabooby** [comment]
Do I have to change the ipc line or and something to my mpv.conf about ipc too?

**Comment by Zabooby** [comment]
Ok its working now but the old mpv ui is overlapping with mine

**Comment by iwalton3** [comment]
> the old mpv ui is overlapping with mine

Disable the mpv GUI using the jellyfin-mpv-shim config file.

**Comment by Zabooby** [comment]
If I wanted the same results with plex-mpv-shim would I use the exact same settings? I noticed for the plex shim the `"mpv_ext_no_ovr" ` wasn't there, would I have to manually add it or is it by design?

**Comment by iwalton3** [comment]
I backported it a while ago but I haven’t released it in a while. https://github.com/iwalton3/plex-mpv-shim/commit/c0dbf148fa1dc693cd776bd858648a63443616eb

**Comment by Zabooby** [comment]
Do I set both of these to false to disable the gui?
```
    "enable_gui": true,
    "enable_osc": true,
```

**Comment by iwalton3** [comment]
Shut off osc only. Disabling the GUI disables the management interface and systray.

**Comment by Zabooby** [comment]
Ok so the ui is working now with no overlaps, but my input.conf doesn't seem to work. 

For example in my setup right click usually opens https://github.com/darsain/uosc rn it just pauses the video.
