### ISSUE TITLE
Intro skipper plugin support.

### ISSUE THREAD

**Issue by calmcacil** [jellyfin/jellyfin-mpv-shim#274]
**Is your feature request related to a problem? Please describe.**
Intro Skipper (https://github.com/ConfusedPolarBear/intro-skipper) seems to have an api sorted for handling skips and such already, and by using the custom webui that they provide skipping intros work in the webui by simply clicking the popup when it happens, or by enabling autoskip. But, since they seem to provide an api for intro stamps already (https://github.com/ConfusedPolarBear/intro-skipper/blob/master/docs/api.md)  So I was wondering if it would be possible to add the functionality to the shim client.

**Describe the solution you'd like**
Making it work in the same way that it works on the plex shim client would be fine just having a simple seek to jump past the intro would be a nice solution. But I also understand that this might be a little tricky to implement as its a 3rd party plugin.

**Comment by Dnkhatri** [comment]
As intro skipper also producer edl files I think it would be better if edl support was added to Mpv natively as well

https://github.com/mpv-player/mpv/issues/10686

**Comment by iwalton3** [comment]
Implemented in 2.3.1. It uses the same UI as plex-mpv-shim and is disabled by default.

**Comment by Dnkhatri** [comment]
thkd
