### ISSUE TITLE
Unable to connect to Jellyfin

### ISSUE THREAD

**Issue by Sayykii** [jellyfin/jellyfin-mpv-shim#299]
**To Reproduce**
1. Run jellyfin-mpv-shim
2. Add server
3. Click *Play on* and see that there are no devices connected.

**Expected behavior**
Be able to see the device in device list, and connect to it.

**Screenshots**

**Desktop:**
 - OS: Linux(EndeavourOS)
 - Version: 2.2.0

**Additional info:**
I am running the latest version of Jellyfin inside a Docker container, I also tried downgrading to both 10.8.4 and 10.8.0 with the same result.

**Error Messages**
[log.txt](https://github.com/jellyfin/jellyfin-mpv-shim/files/9620417/log.txt)

**Comment by dgalli1** [comment]
This is already fixed via this pullrequest:
https://github.com/jellyfin/jellyfin-apiclient-python/pull/15

**Comment by Sayykii** [comment]
That fixed it. Thank you so much!

**Comment by dgalli1** [comment]
**https://github.com/jellyfin/jellyfin-mpv-shim/issues/294#issuecomment-1246522925**

That comment also describes the same issue

**Comment by iwalton3** [comment]
Will make a point release for this later this weekend.

**Comment by iwalton3** [comment]
This fix has been released to the underlying library. People who newly install will get the new version. Otherwise, use `sudo pip3 install --upgrade jellyfin-apiclient-python`.
