### ISSUE TITLE
Fullscreen mode failure

### ISSUE THREAD

**Issue by mkrsticch** [jellyfin/jellyfin-mpv-shim#308]
**Describe the bug**
My goal is to set Jellyfin MPV Shim always to open maximized (fullscreen) and to play video at once.

When I open a video file, it opens the way I closed it last time, which means when I close Jellyfin MPV Shim in a windowed position, it opens in a windowed position when I open the same video file again.

I am using an external copy of MPV. In the conf.json I have "fullscreen": true.

**To Reproduce**
1. Open up a video file and let it play.
2. Press "f" to toggle the fullscreen (or double click it).
3. Use the mouse left click to close the player.
4. Open up the same video file and play again.

Jellyfin MPV Shim will start in a windowed position.

**Expected behavior**
Jellyfin MPV Shim should start in fullscreen mode.

**Comment by mkrsticch** [comment]
The possible reason in conf.json; "stop_cmd": "nircmd.exe setdisplay 1920 1080 32 60",

**Comment by iwalton3** [comment]
If you exit fullscreen once, that is currently preserved until you restart the application. This prevents the client from annoying the user by making the player fullscreen again on each subsequent media playback. You can close the player without exiting fullscreen by pressing `q`.
