### ISSUE TITLE
Add Kodi support

### ISSUE THREAD

**Issue by gzpr** [jellyfin/jellyfin-mpv-shim#312]
This might be a niche use-case, and I know there are two Jellyfin Kodi add ons already, but neither of them work very well when you're using  mpv as an external player in Kodi, so being able to use Kodi with mpv-shim would be really nice.

**Comment by iwalton3** [comment]
I'm sorry but there really is no way to do this. The code is completely incompatible.

**Comment by gzpr** [comment]
Not even with conjunction

**Comment by gzpr** [comment]
Not even in a conjunction with said kodi add-ons? Both of these allow the web client to cast to kodi using the play on functionality, but I guess I should be asking for the ability for a play on function within kodi there instead I suppose.
