### ISSUE TITLE
Installation-Error in build() - "AttributeError: 'PathDistribution' object has no attribute 'key'

### ISSUE THREAD

**Issue by cnachtigall1991** [jellyfin/jellyfin-mpv-shim#314]
I tried to upgrade the package from 2.2.0-1 to 2.3.1-1 with "yay -Syu".
I selected to CleanBuild the package.
As soon as "running egg_info" starts, I get a Traceback with "AttributeError: 'PathDistribution' object has no attribute 'key'.

**Link to Pad with full installation output**
https://pad.harting.dev/HEqU0_UFRRO9HjT6w1d26Q?view

**Desktop (please complete the following information):**
 - Arch Linux Zen
 - 6.1.11-zen1-1.1-zen
 - x86_64
 - Ryzen 7 3700X

What could cause this build to break?

**Comment by jonasmalacofilho** [comment]
Related: https://github.com/pypa/setuptools/commit/c428a57352138d01c21064012091b9bde3017060

**Comment by cnachtigall1991** [comment]
It was an old setuptools version installed with pip and not via extra/python-setuptools
