### ISSUE TITLE
MPV Shim v2.4.2 Doesn't Terminate When Quit is Selected.

### ISSUE THREAD

**Issue by maru801** [jellyfin/jellyfin-mpv-shim#317]
**Describe the bug**
With v2.4.2 on Windows 10 & 11, when you go to Shim's taskbar icon, right-click on it, then select quit to terminate the program, Shim will still be active as a device to cast to within the network. Even after Shim has been selected to stop running, casting to it will still pull up the Shim player. However, once you do and exit out of the player screen, then Shim will properly quit and stop being shown as a castable device. Basically, the only way to stop MPV Shim from working is to quit the program, then quickly cast a video to it, then exit from video player so that it properly terminates.

**To Reproduce**
1. On Windows (10 or 11), start MPV shim
2. Go to Shim's taskbar icon, right-click it and select "Quit"
3. Shim will forever remain active for all devices on the network until a single cast to it is exited from

**Expected behavior**
MPV Shim should stop working & broadcasting itself upon it's termination by the quit option on the taskbar icon.

**Desktop (please complete the following information):**
 - OS: Windows 10 & Windows 11
 - Version: v2.4.2

**Error Messages**
[log.txt](https://github.com/jellyfin/jellyfin-mpv-shim/files/10787536/log.txt)

**Comment by iwalton3** [comment]
This _should_ already be fixed in https://github.com/jellyfin/jellyfin-mpv-shim/commit/497e1298f615f31f31442e37ef4561a4a7ae44d2 but hasn't been released yet. I'll release it in the next update.

**Comment by maru801** [comment]
Fixed with the release of v2.5.0.
