### ISSUE TITLE
Subtitles outline too thick and doesn't match MPV rendering

### ISSUE THREAD

**Issue by sviperz** [jellyfin/jellyfin-mpv-shim#325]
**Describe the bug**
**Jellyfin MPV Shim** subtitles rendering doesn't match the way how MPV does it. The outline around the text is too thick, MPV subtitles look more elegant (IMO of course). Please see the screenshots below.

**Screenshots**

**Jellyfin MPV Shim** subtitles:

![Jellyfin MPV Shim](https://user-images.githubusercontent.com/11470610/222144764-31f53673-4733-4908-8739-7d3404de107d.png)

**MPV** subtitles:

![MPV](https://user-images.githubusercontent.com/11470610/222144839-0e10566f-ecda-4d0c-892f-4985ed4a5e98.png)

Would it be possible please to match MPV style?

**Desktop:**
 - OS: Pop!_OS 22.04 LTS x86_64
 - Resolution: 1920x1080
 - DE: GNOME 42.5
 - Jellyfin MPV Shim: 2.5.0
 - MPV: 0.35.1

**Logs**
[log.txt](https://github.com/jellyfin/jellyfin-mpv-shim/files/10862124/log.txt)

**Comment by iwalton3** [comment]
Oddly enough the subtitles are thicker in regular MPV for me. I'm not sure why.

**Comment by sviperz** [comment]
> Oddly enough the subtitles are thicker in regular MPV for me. I'm not sure why.

The subtitles themselves or the outline? If this is important, I have the size of subtitles set to 0.7 both in Jellyfin MPV Shim and regular MPV.

**Comment by iwalton3** [comment]
The outline. This is with all defaults unchanged.

**Comment by sviperz** [comment]
This is not an issue anymore. I "fixed" it with the `sub-border-size` MPV option.
