### ISSUE TITLE
MPV Shim unable to start external MPV

### ISSUE THREAD

**Issue by sviperz** [jellyfin/jellyfin-mpv-shim#329]
**Description**
In _conf.json_ I set everything to use my external MPV as described in [README](https://github.com/jellyfin/jellyfin-mpv-shim#external-mpv):

_"mpv_ext": true,
"mpv_ext_ipc": null,
"mpv_ext_no_ovr": true,
"mpv_ext_path": null,
"mpv_ext_start": true_

but when I start MPV Shim, nothing happens - no tray icon appears (but still the process is being created) and everything I have in _log.txt_ is this:

_2023-03-13 10:11:29,446 [    INFO] player: Using external mpv playback backend.
2023-03-13 10:11:29,447 [   DEBUG] mpv-jsonipc: Staring MPV from mpv.
2023-03-13 10:11:29,447 [   DEBUG] mpv-jsonipc: Using IPC socket /tmp/mpv124475446479394 for MPV._

**STR**
1. Enable use of external MPV in _conf.json_.
2. Start MPV Shim.

**Expected behavior**
MPV Shim is started successfully and uses external MPV.

**Desktop:**
 - OS: Pop!_OS 22.04 LTS x86_64
 - DE: GNOME 42.5
 - Jellyfin MPV Shim: 2.6.0

**Comment by iwalton3** [comment]
Could you send me the entire log?

**Comment by sviperz** [comment]
Sure, but it's literally only those three lines in the log (attached).

[log.txt](https://github.com/jellyfin/jellyfin-mpv-shim/files/10954771/log.txt)

**Comment by iwalton3** [comment]
That's not ideal. I'm also assuming running it from the command line doesn't give any more information.

I am assuming this was installed via pip. Try running the following python code and let me know what happens:
```python
from python_mpv_jsonipc import MPV
mpv = MPV()
print(mpv.volume)
mpv.volume = 10
```

**Comment by sviperz** [comment]
Got you. I have it installed via Flatpak built in to the system Software Manager.

This is the output from the CLI:

```
$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=jellyfin-mpv-shim com.github.iwalton3.jellyfin-mpv-shim
2023-03-13 11:18:06,059 [    INFO] conf: Loaded settings from json: /home/sviperz/.var/app/com.github.iwalton3.jellyfin-mpv-shim/config/jellyfin-mpv-shim/conf.json
2023-03-13 11:18:06,073 [    INFO] player: Using external mpv playback backend.
2023-03-13 11:18:06,074 [   DEBUG] mpv-jsonipc: Staring MPV from mpv.
2023-03-13 11:18:06,074 [   DEBUG] mpv-jsonipc: Using IPC socket /tmp/mpv115844166955845 for MPV.
Traceback (most recent call last):
  File "/app/bin/jellyfin-mpv-shim", line 8, in <module>
    sys.exit(main())
  File "/app/lib/python3.10/site-packages/jellyfin_mpv_shim/mpv_shim.py", line 65, in main
    from .player import playerManager
  File "/app/lib/python3.10/site-packages/jellyfin_mpv_shim/player.py", line 1138, in <module>
    playerManager = PlayerManager()
  File "/app/lib/python3.10/site-packages/jellyfin_mpv_shim/player.py", line 206, in __init__
    self._player = mpv.MPV(
  File "/app/lib/python3.10/site-packages/python_mpv_jsonipc.py", line 430, in __init__
    self.mpv_process = MPVProcess(ipc_socket, mpv_location, **kwargs)
  File "/app/lib/python3.10/site-packages/python_mpv_jsonipc.py", line 236, in __init__
    self.process = subprocess.Popen(args)
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mpv'
```

Seems like MPV Shim is unable to find MPV being run as a Flatpak container. My _mpv_ is clearly available directly from the CLI though:

```
$ mpv
mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Mon Feb 06 05:37:54 2023
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
FFmpeg version: 5.1.2-0ubuntu1~22.04.sav2

Usage:   mpv [options] [url|path/]filename

Basic options:
 --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
 --no-audio        do not play sound
 --no-video        do not play video
 --fs              fullscreen playback
 --sub-file=<file> specify subtitle file to use
 --playlist=<file> specify playlist file

 --list-options    list all mpv options
 --h=<string>      print options which contain the given string in their name
```

Any workarounds so far?

**Comment by iwalton3** [comment]
Not really... Flatpak application isolation really breaks the ability for this to work. A static MPV build could theoretically work but I don't think those are available on Linux.

You would have to install the application via pip to use external MPV. Alternatively, is there some feature the built-in MPV lacks that I could add to the Flatpak build?

**Comment by sviperz** [comment]
OK, I'll install it via pip then. I just wanted to have one MPV to manage and since I have some issues with the built in MPV I decided to give the external one a go.

Among issues with built in MPV:
- Unable to use _gpu-next_ VO. I don't why, I've been using it for a long time already in my standalone MPV. But the built in one says in the log that it can't find _gpu-next_ VO.
- _thumbfast_ doesn't work (works perfectly in external MPV)

I promise to report those bugs later. But first I wanna give pip version a try and see how it goes. Maybe those issues are also connected with Flatpak somehow.

**Comment by iwalton3** [comment]
Are you using the real thumbfast or are you talking about my compatibility layer? https://github.com/jellyfin/jellyfin-mpv-shim/blob/master/jellyfin_mpv_shim/thumbfast.lua

As far as gpu-next is concerned I probably am just using a version of MPV that is too old. https://github.com/flathub/com.github.iwalton3.jellyfin-mpv-shim/blob/e62873cf153554b1977b65ccbe263728a450e640/com.github.iwalton3.jellyfin-mpv-shim.json#L229

**Comment by sviperz** [comment]
> Are you using the real thumbfast or are you talking about my compatibility layer? https://github.com/jellyfin/jellyfin-mpv-shim/blob/master/jellyfin_mpv_shim/thumbfast.lua

I was only able to use internal thumbfast for showing chapter pics extracted by the server and not for showing the frame under cursor as it works in a standalone MPV. Just checked it with external MPV when JMS is installed via pip - is doesn't work either, shows nothing when I hover the timeline. In a standalone MPV it works as expected.

> As far as gpu-next is concerned I probably am just using a version of MPV that is too old. https://github.com/flathub/com.github.iwalton3.jellyfin-mpv-shim/blob/e62873cf153554b1977b65ccbe263728a450e640/com.github.iwalton3.jellyfin-mpv-shim.json#L229

But this is the latest release version, right? [v0.35.1](https://github.com/mpv-player/mpv/releases/tag/v0.35.1). _gpu-next_ is available since v0.35 AFAIK. I have the same version of MPV installed and _gpu-next_ works there (in the standalone app). It also works with external MPV, but doesn't work with built in MPV.

I think we can close this bug and discuss those issues in dedicated bugs report I'll open later. Please just add a comment in README that external MPV in not available from Flatpak's JMS.

**Comment by iwalton3** [comment]
Since the issues aren't open yet.

For gpu-next I hadn't compiled in support. This is now fixed and verified to work. (You still need to enable it in `mpv.conf`.) It should be live on Flathub within the next hour.

For `thumbfast`, the built-in one uses chapter images by default. To get full previews you need to install [Jellyscrub](https://github.com/nicknsy/jellyscrub) on your server and enable it in the menu or config. If you would like to use standard `thumbfast`, simply disable the built-in compatibility layer by setting `thumbnail_enable` to false in the config. https://github.com/jellyfin/jellyfin-mpv-shim#trickplay-thumbnails

**Comment by sviperz** [comment]
> For gpu-next I hadn't compiled in support. This is now fixed and verified to work. (You still need to enable it in `mpv.conf`.) It should be live on Flathub within the next hour.

Thanks, it was fast! But since Flatpak has other limitations and bugs I've just noticed, I switched to pip version. Should _gpu-next_ work in pip version? Because it doesn't at the moment, when I enable it in mpv.conf, I get this in the log:

```
2023-03-13 16:18:42,674 [   ERROR] mpv: vo: Video output gpu-next not found!
2023-03-13 16:18:42,674 [   ERROR] mpv: cplayer: Error opening/initializing the selected video_out (--vo) device.
2023-03-13 16:18:42,674 [    INFO] mpv: cplayer: Video: no video
```

> For `thumbfast`, the built-in one uses chapter images by default. To get full previews you need to install [Jellyscrub](https://github.com/nicknsy/jellyscrub) on your server and enable it in the menu or config. If you would like to use standard `thumbfast`, simply disable the built-in compatibility layer by setting `thumbnail_enable` to false in the config. https://github.com/jellyfin/jellyfin-mpv-shim#trickplay-thumbnails

I now have this in conf.json (as pointed in release notes [here](https://github.com/jellyfin/jellyfin-mpv-shim/releases/tag/v2.5.0)  and your note from above):

```
"thumbnail_enable": false,
"thumbnail_jellyscrub": false,
"thumbnail_osc_builtin": false
```

and exactly the same setup of standard `thumbfast` as I have for a standalone MPV (script-opts and scripts folders), but it still doesn't work for some reason.

**Comment by sviperz** [comment]
Oh well, it also very inconsistent. With those options from my previous comment built-in MPV is messing with the OSC - it can start with custom OSC (ModernX in my case), but without thumbfast; with default MPV OSC; or with no OSC at all.

**Comment by iwalton3** [comment]
> Should gpu-next work in pip version?

That depends on your packaged MPV version from your Linux distribution. You may need to compile MPV from source or use a third-party repo to get all of the features.

> it can start with custom OSC (ModernX in my case), but without thumbfast; with default MPV OSC; or with no OSC at all.

This should fully disable built-in OSC and my trickplay scripts:
```
"thumbnail_enable": false,
"thumbnail_jellyscrub": false,
"thumbnail_osc_builtin": false,
"enable_osc": false
```
Then just throw the thumbfast and ModernX files into the scripts folder in your config. Reminder that I don't use your user-wide mpv config even with external mpv unless you use the "mpv_ext_no_ovr" config option.

**Comment by sviperz** [comment]
I think we are now mixing up the things together, sorry for confusion.

From now on I want to completely switch to Jellyfin MPV Shim (JMS) built-in MPV (and not to use the external, let's make JMS awesome (which it already is, but still)). So I'll be talking here only about:
- JMS installed from pip.
- Built-in MPV.

So, my external MPV, while being launched as a standalone application, supports _gpu-next_ with no issues. I'm not sure if JMS uses the external (let's say system) MPV somehow (maybe via libmpv), but what I'm trying to say is that when I set vo=gpu-next in mpv.conf placed in ~/.config/jellyfin-mpv-shim/ it doesn't work with _mpv: vo: Video output gpu-next not found!_ error in the logs. And I'm wondering how I can make it work.

> This should fully disable built-in OSC and my trickplay scripts:
> 
> ```
> "thumbnail_enable": false,
> "thumbnail_jellyscrub": false,
> "thumbnail_osc_builtin": false,
> "enable_osc": false
> ```
> 
> Then just throw the thumbfast and ModernX files into the scripts folder in your config.

That's exactly what I did, but even though the custom OSC is there the thumbfast doesn't work. Do you need MPV debug logs maybe (`"mpv_log_level": "debug"`)?

**Comment by iwalton3** [comment]
Internal MPV uses libmpv so it may be using an MPV installed by your package manager. If you enable external MPV it will use your `mpv` binary that you installed which has gpu-next working in it.

> That's exactly what I did, but even though the custom OSC is there the thumbfast doesn't work. Do you need MPV debug logs maybe ("mpv_log_level": "debug")?

You could try sending it. It may give me an idea what is going on.

**Comment by sviperz** [comment]
Finally managed to enable thumbfast. The culprit was thumbfast's own setting _network=yes_ which is _no_ by default. System MPV played files from the mounted drive (which seems to be as local for it), but for JMS it was network access after all. That's why it was a source of confusion.

The only thing that left uncertain is why JMS can't use gpu-next while my system MPV can use it easily. I have my system MPV installed from this repo BTW - https://ppa.launchpadcontent.net/savoury1/mpv/ubuntu/ - this is the most recent version with gpu-next compiled in for sure. Any ideas or any additional info needed?

**Comment by iwalton3** [comment]
Run this:
```bash
find /usr/ -iname 'libmpv*' -exec dpkg -S '{}' ';'
```
Or switch to external mpv which will use the same `mpv` binary as you normally use.

**Comment by sviperz** [comment]
> Run this:
> 
> ```shell
> find /usr/ -iname 'libmpv*' -exec dpkg -S '{}' ';'
> ```

```
$ find /usr/ -iname 'libmpv*' -exec dpkg -S '{}' ';'
libmpv1:amd64: /usr/lib/x86_64-linux-gnu/libmpv.so.1.109.0
libmpv1:amd64: /usr/lib/x86_64-linux-gnu/libmpv.so.1
libmpv1:amd64: /usr/share/doc/libmpv1
```

**Comment by iwalton3** [comment]
Yeah it looks like libmpv is being provided by that `libmpv1` package, which is likely outdated. Try installing `libmpv2` as it appears to be available from that PPA you linked: https://ppa.launchpadcontent.net/savoury1/mpv/ubuntu/pool/main/m/mpv/

Note that you may need to uninstall `libmpv1` to get the software to use the newer version.

**Comment by sviperz** [comment]
> Yeah it looks like libmpv is being provided by that `libmpv1` package, which is likely outdated. Try installing `libmpv2` as it appears to be available from that PPA you linked: https://ppa.launchpadcontent.net/savoury1/mpv/ubuntu/pool/main/m/mpv/
> 
> Note that you may need to uninstall `libmpv1` to get the software to use the newer version.

Yes, that did the trick! Removed FFmpeg 5 repo and added FFmpeg 6 repo and mpv and libmpv were updated after that. Now gpu-next works. Thanks! You helped me to resolve all the recent issues I had. Now back to actually watching movies instead of setting everything up.
