### ISSUE TITLE
BUG : Win7 can not be used normally

### ISSUE THREAD

**Issue by SwePolice** [jellyfin/jellyfin-mpv-shim#348]
It can be installed normally under win7 system, but the program requires a version higher than python3.9 to run, but the last python version supported by win7 system is 3.8.
![tianruo_2023-9-6-638296131927600178](https://github.com/jellyfin/jellyfin-mpv-shim/assets/132160235/2f6667e8-3c89-473a-8f7e-e84dc8482ff6)

**Comment by JPVenson** [comment]
Hey @SwePolice 

Windows7 is an outdated operating system that is officially out of life. That is why there is no support for it.
