### ISSUE TITLE
Bottom bar not showing with mpv v0.38.0

### ISSUE THREAD

**Issue by kattjevfel** [jellyfin/jellyfin-mpv-shim#376]
**Describe the bug**
The bottom bar of mpv does not show when using it with jellyfin-mpv-shim as of mpv v0.38.0, I've bisected it down to https://github.com/mpv-player/mpv/commit/86b498ecc0e6276bb905df57f479d0506b45ba53, which removes `shared-script-properties`, which the shim uses here:
```
jellyfin_mpv_shim/trickplay-osc.lua
2240:    utils.shared_script_property_set("osc-margins",
2246:    utils.shared_script_property_set("osc-margins", nil)
2910:    utils.shared_script_property_set("osc-visibility", mode)
2942:    utils.shared_script_property_set("osc-idlescreen", mode)
```

**To Reproduce**
1. Install mpv v0.38.0
2. Launch jellyfin-mpv-shim
3. Play video in jellyfin casting to the shim
4. The bottom bar cannot be accesses

**Expected behavior**
The bottom bar being accessible so that I can select subtitles and skip ahead etc.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: jellyfin-mpv-shim 2.6.0-2

**Error Messages**
[log.txt](https://github.com/jellyfin/jellyfin-mpv-shim/files/15023363/log.txt)

**Comment by krakow10** [comment]
I am still having this issue, is there some sort of config I need to change to get the mpv gui showing again?

**Comment by fkroener** [comment]
Adding osc=yes in ~/.config/jellyfin-mpv/shim/mpv.conf has the gui show up again for me.
