### ISSUE TITLE
Running jellyfin-mpv-shim suddenly doesn't work

### ISSUE THREAD

**Issue by Sheepyhead** [jellyfin/jellyfin-mpv-shim#382]
**Describe the bug**
Running jellyfin-mpv-shim suddenly doesn't work. I was downgrading my mpv due to #381, and during the process suddenly I could no longer start jellyfin-mpv-shim. I can't find any other cases of this happening, something a python module seems to be missing? I've tried reinstalling, rebooting, the works. I'm using Pacman as my package manager.

**Desktop (please complete the following information):**
 - OS: Arch Linux EndeavourOS
 - Version 6.8.7-arch1-2

**Error Messages**
```
jellyfin-mpv-shim 
Traceback (most recent call last):
  File "/usr/bin/jellyfin-mpv-shim", line 5, in <module>
    from jellyfin_mpv_shim.mpv_shim import main
ModuleNotFoundError: No module named 'jellyfin_mpv_shim'
```

**Comment by Alittlemurkling** [comment]
I had the same error. You must fully uninstall jellyfin-mpv-shim and all its dependencies, then reinstall it to move past this. However, if you're experiencing the same issue as me, you will then get this error:
`````2024-04-28 13:07:07,634 [   ERROR] websocket: error from callback <function WSClient.run.<locals>.<lambda> at 0x789cdf6cb2e0>: ('Invalid value for mpv parameter', -4, (<MpvHandle object at 0x789cdf647250>, <mpv.LP_MpvNode object at 0x789cdf6c0350>, <mpv.LP_MpvNode object at 0x789cdf6c00d0>))
2024-04-28 13:07:07,634 [   ERROR] mpv: main: Command loadfile: argument index can't be parsed: option requires parameter.`

**Comment by Alittlemurkling** [comment]
It looks like this might be a bug or breakage in the recently released MPV 0.38.

**Comment by Sheepyhead** [comment]
> I had the same error. You must fully uninstall jellyfin-mpv-shim and all its dependencies, then reinstall it to move past this. 

Already tried this

> Confirmed. Downgrading to MPV 0.37 fixes the second (my) error.

Downgrading to MPV 0.37 is what made this happen in the first place

**Comment by dgalli1** [comment]
Arch just got a new python version. Just uninstall and reinstall jellyfin-mpv-shim via pip.

But as you can't use pip anymore as this is nowadays blocked by arch you will have to use pipx.

1. remove jellyfin-mpv-shim from the current location
2. install pipx
3. pipx install jellyfin-mpv-shim
4. Config is saved in .local/config so you don't have to worry about losing it.

**Comment by Sheepyhead** [comment]
That worked! Thank you I was at my wit's end about this issue!
