### ISSUE TITLE
Unable to see trickplays after jellyfin 10.9 update

### ISSUE THREAD

**Issue by vinaysb** [jellyfin/jellyfin-mpv-shim#387]
**Describe the bug**
I am not able to see trickplay thumbnails for media after updating to the latest jellyfin version. I converted all the jellyscrub thumbnails to jellyfin native trickplays, and deleted the jellyscrub extension as recommended. But not I do not see any of those thumbnails in shim.

**To Reproduce**
1. Update to latest jellyfin version
2. Migrate jellyscrub to trickplays

**Expected behavior**
Media thumbnails are visible

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: v2.6.0

**Comment by maru801** [comment]
This should be fixed within the next release. There's a [commit](2234b0082e6b7963d1ebf7ef69dd8d0c8d17bff5) made some hours ago already that addresses this issue.

**Comment by sheharyarn** [comment]
I have a slightly different issue where the hiding and re-enabling the OSC disables the thumbs, any ideas @maru801?

https://github.com/jellyfin/jellyfin-mpv-shim/issues/409
