### ISSUE TITLE
Doesn't remember Default Device

### ISSUE THREAD

**Issue by kraM1tt** [jellyfin/jellyfin-mpv-shim#414]
When selecting MPV Shim as default device to cast to, as soon as I close the tab or even refresh the page is instantly forgets and I have to reconnect it manually every time. Is this expected behaviour? I'm new to MPV Shim as JMP doesn't support HDR playback.

I can provide logs or whatever if needed

JF Server version 10.9.11
Windows 11 23H2

**Comment by Regradert** [comment]
I have the same version and Windows 11. I have the same error, it is very unpleasant, please see if you can look into it soon.

**Comment by kraM1tt** [comment]
This is now fixed and working great in 10.10.0
