### ISSUE TITLE
No systray for Desktop client when used from used with mpv-shim 

### ISSUE THREAD

**Issue by gerroon** [jellyfin/jellyfin-mpv-shim#69]
**Describe the bug**
It looks like there is no mpv-shim systray when  `"enable_desktop": true` is set

**To Reproduce**
Open your conf.json and set ` "enable_desktop": true, `
Restart your mpv-shim
It opens the desktop client, but no  system tray is shown.

**Expected behavior**
It should have a system tray icon like the regular mpv one

**Desktop (please complete the following information):**
 - OS: Linux Debian Testing, installed using pip3

It would be very nice if the desktop clients behaves similar to Mpv where it is minimized to the tray so it is not always open. It should be open either when a client is casting or the user clicks on the tray icon.

thanks

**Comment by iwalton3** [comment]
Right now systray interface is not allowed when the desktop web wrapper interface is used. The web wrapper handles auth tokens differently and is heavier, so I didn't really intend it to be run minimized to the system tray.

**Comment by gerroon** [comment]
Well the issue is that the desktop app has to be in the foreground always to be able to cast and see the content on the screen. Is it possible to activate/bring to front when a media playback starts on it?

**Comment by iwalton3** [comment]
Is the desktop app actually playing media in MPV? If it is playing in the desktop window where the web player is then there is a session issue.

**Comment by gerroon** [comment]
I am not sure. I did what I mentioned in my first post.  It does not seem like it plays it in mpv. It plays inside the desktop app as far as I can tell.

 I am trying to figure out if it is possible to bring the desktop app to front since most of the time it willbe minimized.

**Comment by iwalton3** [comment]
> It plays inside the desktop app as far as I can tell.

That would be the problem. Try logging out from the desktop client view and logging again. Ensure a cast connection appears in the top corner of the web client. You can send a screenshot of the desktop client open if you are unsure.

**Comment by gerroon** [comment]
thanks I will try it

**Comment by iwalton3** [comment]
Desktop mode is now unsupported and is removed in the latest release. Please use Shim Mode or [Jellyfin Media Player](https://github.com/jellyfin/jellyfin-media-player/releases) instead.
