### ISSUE TITLE
Missing Download progress bar/info/anything

### ISSUE THREAD

**Issue by nextlooper42** [jellyfin/jellyfin-mpv-shim#87]
**Describe the bug**
After clicking on download button (movie or show), Shim will download said thing... but it wont show progress and there is no way to track progress. Especially for **basic pc user** that want to download media to device for travelling.

**To Reproduce**
1. Click on movie/episode
2. Download
3. Wait... unknown how long

**Expected behavior**
Show download progress bar or something.

**Desktop (please complete the following information):**
 - OS: W10
 - Version 1.5.10
- Jellyfin Server 10.5.5

**Comment by iwalton3** [comment]
Downloads are not a feature of the client. There may be a download button in the web client, but all this does is initiate a media download as a file, which the embedded webview doesn't handle well. There is no way to use the application while not online.

**Comment by nextlooper42** [comment]
Yes i know all of that and "There is no way to use the application while not online." is obvious. But you can watch downloaded content offline outside of shim with regular mpv for example (point of this).

Issue here is simple, Jellyfin in browser will download media and show progress on download page among the regular browser download stuff. Shim... well, doesnt have anything to tell that is finished.

**Comment by iwalton3** [comment]
I don't really have control over how the webview presents downloads unfortunately. There are 4 different webview implementations used, and the download feature isn't exposed through the webview API. (Not to mention every little thing I add to the web client is an out-of-tree patch I have to maintain.)

**Comment by iwalton3** [comment]
This issue is "fixed" in Jellyfin Media Player in that it downloads files using your web browser.

Desktop mode is now unsupported and is removed in the latest release. Please use Shim Mode or [Jellyfin Media Player](https://github.com/jellyfin/jellyfin-media-player/releases) instead.
