### ISSUE TITLE
Mouse back and forward buttons should navigate like in the browser

### ISSUE THREAD

**Issue by quantumfrost** [jellyfin/jellyfin-mpv-shim#95]
When using Jellyfin through the browser, you can use the back/forward buttons (which most mice have) to navigate. It would be nice if Jellyfin MPV desktop recognized them too. It would be much more convenient than aiming for that small back button every time, especially on larger displays.

**Comment by iwalton3** [comment]
What platform are you on?

**Comment by quantumfrost** [comment]
Ubuntu 20.04 and Windows 10

**Comment by iwalton3** [comment]
So the issue is present on all platforms. I unfortunately don't really have control over the webview implementations, so it may be better to log this issue with [pywebview](https://github.com/r0x0r/pywebview).

You can always use the client in the Shim Mode and then use whatever web browser you want.

**Comment by quantumfrost** [comment]
Okay, thanks. I haven't used pywebview but I tried creating a simple project and it doesn't recognize back/forward buttons. Can't find anything in their documentation either, so I'll log the issue with them.

It does send out a "loaded" event every time you navigate to a new page, so one way to implement it would be to maintain a history stack manually and navigate by capturing mouse back/forward. But that may not be ideal.

**Comment by iwalton3** [comment]
Mouse back and forward buttons work in Jellyfin Media Player.

Desktop mode is now unsupported and is removed in the latest release. Please use Shim Mode or [Jellyfin Media Player](https://github.com/jellyfin/jellyfin-media-player/releases) instead.
